limit_req_zone $binary_remote_addr zone=api_limit:10m rate=50r/s;

server {
    listen 80;
    server_name localhost;

    root /var/www/html/src/public;
    index index.php index.html;

    client_max_body_size 20M;
    server_tokens off;

    location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg|woff|woff2)$ {
        try_files $uri =404;
        expires 7d;
        access_log off;
    }

    location ~* \.(html)$ {
        expires -1;
    }

    # Main request routing. 
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM processing block
    location ~ \.php$ {
        limit_req zone=api_limit burst=30 nodelay;

        try_files $uri =404;

        # FastCGI configuration
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;

        fastcgi_connect_timeout 5s;
        fastcgi_send_timeout 60s;
        fastcgi_read_timeout 60s;
    }

    location ~ /\.(env|git|htaccess) {
        deny all;
    }
}