# prod dockerFile, for local dev: Check php/dockerFile

FROM php:8.2-cli-alpine

WORKDIR /app

RUN apk add --no-cache \
    git unzip curl libzip-dev oniguruma-dev

RUN docker-php-ext-install pdo pdo_mysql zip

RUN pecl install mongodb \
    && docker-php-ext-enable mongodb

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-interaction

WORKDIR /app/src
CMD php -S 0.0.0.0:$PORT -t public public/index.php